version: "3.9"

services:
  piler:
    image: fabianbees/mail-piler
    ports:
      - "80:80"
      - "25:25"
    restart: always
    volumes:
      - data-store:/var/piler/store/00
      - data-sphinx:/var/piler/sphinx
      - data-config:/etc/piler
      - data-mariadb:/var/lib/mysql
    environment: 
      - PILER_RETENTION=3650
      - PILER_HOST=piler.yourdomain.com
      - MYSQL_DATABASE=piler
      - MYSQL_USER=piler-db-user
      - MYSQL_PASSWORD=piler123
      - MARIADB_ROOT_PASSWORD=enter-very-secure-root-pw

volumes:
  data-store:
  data-sphinx:
  data-config:
  data-mariadb: