version: "3"

services:
  piler:
    build: 
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - piler-db
    ports:
      - "80:80"
      - "25:25"
    restart: always
    volumes:
      - ./store:/var/piler/store/00
      - ./sphinx:/var/piler/sphinx
      - ./config:/etc/piler
    environment: 
      PUID: "1004" 
      PGID: "1004"
      PILER_HOSTNAME: "localhost"
      PILER_RETENTION: "3650"
      MYSQL_HOSTNAME: "piler-db"
      MYSQL_DATABASE: "piler"
      MYSQL_USERNAME: "piler"
      MYSQL_PASSWORD: "piler123"

  piler-db:
    image: mariadb:latest
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "piler123"
      MYSQL_DATABASE: "piler"
      MYSQL_USER: "piler"
      MYSQL_PASSWORD: "piler123"